import usePageTitle from '../hooks/usePageTitle';
import { Link } from 'react-router-dom';
import Footer from '../components/Footer';

const RosterMonster = () => {
  usePageTitle('Roster Monster');

  return (
    <div className="content">
      <Link to="/" className="sticky-back-btn" aria-label="Back to home">
        ← Back
      </Link>
      <section className="section hero-section">
        <video src="/case-studies/ogp_cs.mp4" autoPlay loop muted playsInline />
      </section>

      <section className="section project-info">
        <p className="section-lead">Reducing 1 week's worth of effort into hours of roster planning through automation feedback</p>
        <div className="info-grid">
          <div className="info-item">
            <p className="supportingText">Timeline</p>
            <p>2 months</p>
          </div>
          <div className="info-item">
            <p className="supportingText">Collaborators</p>
            <p>1 Engineer<br />1 Product Manager<br />1 Design Manager</p>
          </div>
          <div className="info-item">
            <p className="supportingText">Constraints</p>
            <p>Scarce engineering bandwidth<br />User testing opportunities</p>
          </div>
        </div>
      </section>

      <section className="section role-section">
      <hr className="divider" />

        <p className="supportingText">My Role</p>
        <p className="section-lead">Leading research and design on various design features towards an MVP product</p>
        <p>As the sole designer onboard, I owned the design of the product – working closely with a Product Manager, an engineer, and with support from my manager. My team was also working in this product at a part time capacity, which affected product decisions and directions.</p>
      </section>

      <section className="section context-section">
        <p className="supportingText">Context</p>
        <div className="section-lead">What is a roster? Who is a roster planner?</div>
        <div className="context-cards">
          <div className="context-card">
            <img src="/ogp/ogp_icon.png" alt="Roster icon" className="card-icon rounded-img" />
            <h3>Roster</h3>
            <p>A roster is a schedule or list that outlines the assignment of tasks, shifts, or responsibilities for a group of people.</p>
          </div>
          <div className="context-card">
            <img src="/ogp/ogp_icon2.png" alt="Roster planner icon" className="card-icon rounded-img" />
            <h3>Roster Planner</h3>
            <p>A person that uses tools/systems to manage and organize employee schedules/rosters.</p>
          </div>
        </div>
        <div className="section-lead">Rosters are governed by algorithms, and logical "rules" to follow</div>
        <img src="/ogp/ogp_examplerroster.png" alt="Example roster" className="rounded-img" />
        <hr className="divider" />
        <div className="section-lead">A B2B roster generation tool for public sector roster planners in Singapore</div>
        <p>Roster monster helps roster planners in the public sector create a first draft of a roster more efficiently. The algorithm takes into consideration a set of rules, scheduled shifts and staff requests, which roster planners set-up manually.</p>
        <img src="/ogp/ogp_diagram.png" alt="Roster monster diagram" className="rounded-img" />
        <hr className="divider" />
        <p className="supportingText">Higher Level Problem</p>
        <p className="section-lead">Roster planners don't have visibility and insight to the fairness of the roster, generated by the machine</p>
        <p>When a normally manual process is automated, roster planners lose the insight to easily identifiable information for the tradeoffs are made.</p>
        <p className="section-lead">This led to manual, time consuming workarounds when evaluating if a generated roster is good and fair enough</p>
        <p>The automation process leaves the roster planner completely out of the loop when creating a roster.</p>
        <img src="/ogp/ogp_roster_diagram.png" alt="Roster diagram" className="rounded-img" />
      </section>

      <section className="section">
        <hr className="divider" />
        <p className="supportingText">The Design Solution</p>
        <p className="section-lead">A generated roster summary view of rule violations</p>
        <p>Roster planners can now look, identify, and assess the severity of roster planner defined rules (constraints) that have not been met in the generated roster.</p>
        <img src="/ogp/ogp_solution.gif" alt="Final animation" className="solution-video rounded-img" />
        <p className="section-lead">Animated loading state for E2E workflow</p>
        <p>In addition to the summary view, I added transparency to the generation time, time estimate, and a simple loading animation, exported as a Lottie file.</p>
        <img src="/ogp/ogp_animation.gif" alt="Loading animation" className="solution-video rounded-img" />
      </section>

      <section className="section">
      <hr className="divider" />
        <p className="supportingText">Research {'->'} Problem Framing</p>
        <p className="section-lead">How might roster planners evaluate if a roster is 'good enough' through rules?</p>

        <p>Roster planners need 3 types of rule information to evaluate the generated roster</p>
        <p>One of the insights we discovered was what about information about rules was important to see.</p>
        <div className="concept-card">
          <h3>Example use case:</h3>
          <p>If roster isn't able to fulfill a '20 staff per day' rule, a roster planner would need to know where (i.e. Monday) and degree (i.e. only 18 staff were rostered).</p>
        </div>
        <img src="/ogp/ogp_insight.png" alt="Insight diagram" className="solution-video rounded-img" />
        <p>I led semi structured interviews to further understand this process with various government stakeholders.</p>
        <img src="/ogp/ogp_research.png" alt="Research findings" className="solution-video rounded-img" />
      </section>

      <section className="section">
        <p className="supportingText">Design Exploration – Concept Testing</p>
        <p className="section-lead">Various concepts that leveraged on both familiar and different workflows to evaluate a 'good enough' roster</p>
        <p>I explored 3 different concepts and high level scenarios without getting too deep into the UI.</p>
        <div className="concept-cards">
          <div className="concept-card">
            <p>Visual, hover interaction</p>
            <h3>What if you could see the rule violation directly on the roster?</h3>
          </div>
          <div className="concept-card">
            <p>Hover interaction</p>
            <h3>What if you could see the rule violation directly on the quota statistics page?</h3>
          </div>
          <div className="concept-card">
            <p>Drawer modal</p>
            <h3>What if there was a summary of rule violations?</h3>
          </div>
        </div>
        <img src="/ogp/ogp_scenario.png" alt="Design scenarios" className="solution-video rounded-img" />
        <hr className="divider" />

        <p className="section-lead">Finding an 'MVP' concept to work on first</p>
        <p>Roster planners liked the summary view the most, but it was also important to see the roster in view.</p>
        <img src="/ogp/ogp_winner.png" alt="Selected concept" className="solution-video rounded-img" />
        <hr className="divider" />
        <p className="supportingText">FUTURE SCOPING, PRODUCT ROADMAPPING</p>
        <p className="section-lead">Will building this feature amongst others move the needle?</p>
        <p>As I was the only full time designer onboard, I needed to justify with my engineer that the feature was worth pushing out after the research and design I would be undergoing.</p>
        <img src="/ogp/ogp_mrf.png" alt="Product roadmap" className="solution-video rounded-img" />
        <p>Hearing the user challenges through interviews and our feedback loop helped me justify the decision (with good confidence) to push for a high impact, high effort feature.</p>
        <img src="/ogp/ogp_feature_impact.png" alt="Feature impact" className="solution-video rounded-img" />
      </section>

      <section className="section">
        <p className="supportingText">DESIGN DETAIL CONSIDERATIONS</p>
        <p className="section-lead">Focusing on the most important, relevant rule violation information</p>
        <p>From interviews and shadowing, they generally look out for information in this order. For example, if a roster isn't able to fulfill a '20 staff per day' rule, a roster planner would need to know where (i.e. Monday) and degree (i.e. only 18 staff were rostered).</p>
        <img src="/ogp/ogp_table.png" alt="Table design" className="solution-video rounded-img" />
        <p>Some key insights from the usability tests:</p>
        <div className="concept-cards">
          <div className="concept-card">
            <h4>No table headers looks, <br></br>feels cleaner</h4>
            <p>Table header information was not relevant and took up unnecessary space to roster planners.</p>
          </div>
          <div className="concept-card">
            <h4>Accordion helps with showing relevant info</h4>
            <p>Accordion worked well as intended, allowing focus on specific rule violations.</p>
          </div>
          <div className="concept-card">
            <h4>Info hierarchy can be a bit tough to navigate</h4>
            <p>Grids helped, already quite a lot of text to process. Hierarchy was not as clear.</p>
          </div>
        </div>
        <p className="section-lead">Being intentional with whitespace and visual clutter</p>
        <p>I focused a lot on using the right type size, colors, and even spacing to create an information hierarchy akin to how roster planners would need to see the information.</p>
        <img src="/ogp/ogp_finaliteration.png" alt="Final design iteration" className="solution-video rounded-img" />
        <p className="supportingText">INTERACTION DESIGN CONSIDERATIONS</p>
        <p className="section-lead">Maximising the view for roster planners</p>
        <p>During a testing session, I noted that a roster planner would ideally like to see both the roster and the drawer summary for reference. This meant hiding irrelevant information, such as hiding sidebar by default.</p>
        <img src="/ogp/ogp_hide_sidebar.png" alt="Sidebar interaction" className="solution-video rounded-img" />
        <p className="supportingText">HIGHER LEVEL DESIGN FLOW, EDGE CASES</p>
        <p className="section-lead">Bringing clarity to the backend roster generation process</p>
        <p>Generating a roster can take up to 5 minutes, conveyed through the spinning circle of death. I spared an hour to quickly create a pop-up modal with a simple animation using After Effects and additional copywriting, which my engineer could easily implement in minutes.</p>
        <img src="/ogp/ogp_time.png" alt="Time estimation" className="solution-video rounded-img" />
        <img src="/ogp/ogp_animation_iteration.gif" alt="Loading animation iteration" className="solution-video rounded-img" />
      </section>

      <section className="section">
        <hr className="divider" />
        <p className="supportingText">Thoughts, Reflection</p>
        <div className="learning-cards">
          <div className="learning-card">
            <p className="section-lead">Catering to everyone meant catering to no one</p>
            <p>During the initial part of my internship, we faced a lot of issues during testing and research of people not understanding our product. Upon reflection, this taught me to being judicious about what and who to prioritise for. In this case, we decided to focus on tech savvy roster planners for the time being.</p>
          </div>
          <div className="learning-card">
            <p className="section-lead">Conducting group design critiques when it's hard to hear directly from users</p>
            <p>Often times hearing from the user is ideal, but I don't always have access to them especially with a small user base. I learnt how to prepare and present my work amongst designers which gave me invaluable feedback on explorations, design details, and other considerations. This taught me to organise types of feedback given and build confidence to share designs in various types of fidelity.</p>
          </div>
        </div>
        <img src="/ogp/ogp_inperson.png" alt="In-person testing" className="solution-video rounded-img" />
      </section>
      
      <Footer />
    </div>
  );
};

export default RosterMonster; 